### ISSUE TITLE
No squids spawning

### ISSUE THREAD

**Issue by Marilsanya** [programgames/Gregblock-revamped#10] opened 2021-01-30 10:03 UTC
I am not able to get any squids spawn with the default configs. It seems like the randomtweaks mod is causing this. Changing the "I:spawnRadiusLimit=64" to "I:spawnRadiusLimit=0" for squids (so disabling this setting) allows squids to spawn again for me.

**Comment by CrafterKolyan** [comment] 2021-02-14 11:02
I've checked this one on the latest release 2.1.2. Squids are spawning without any changes to the configs.

Steps to reproduce:
1. Create a world with seed `CrafterKolyan` with creative mod
2. Get a water bucket and spill the water from the island (better to do it as on screenshot)
3. Create a big platform on the y coordinate of 25 or less
4. Stand on island and look in water (about 5-10 minutes should be enough)
5. Squids will appear and die when fall on platform

![image](https://user-images.githubusercontent.com/9883873/107874785-f9e74880-6ecc-11eb-96bd-641a89bad6fd.png)

**Comment by CrafterKolyan** [comment] 2021-02-14 21:43
Basically this looks exactly as https://github.com/TheLimePixel/GregBlock/issues/175. I don't know why the first creator of modpack has putted value of 64 blocks, in my opinion we can put something like 192 (which is equal to 12 chunks) not to lag on servers.

**Comment by Marilsanya** [comment] 2021-02-27 17:14
i go to level y=60, place a water bucket, go down to bottom layer and wait. Without config changes, no squid spawn. If i disable any changes to squid in the config, they spawn quickly (within seconds, not 5-10 minutes). And i had a squid farm setup in my normal world with no squid spawning for hours. Config change and they started spawning quickly. Since i did not change anything else, the issue seems config related.

**Comment by tmtvl** [comment] 2021-05-05 18:02
Squid spawn fine for me with the default configuration.

**Comment by programgames** [comment] 2021-06-13 10:10
Closing the issue as i'm not able to reproduce the issue with the original config.
Free feel to re-open.

![2021-06-13_12 09 43](https://user-images.githubusercontent.com/18596429/121803121-4a36a300-cc40-11eb-9128-1659d782f7e9.png)

**Closed as completed** 2021-06-13 10:11 UTC
